// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'ApiTokenNotFound': typeof import("../components/ApiTokenNotFound.vue")['default'],
    'BlogPostTile': typeof import("../components/BlogPostTile.vue")['default'],
    'Feature': typeof import("../components/Feature.vue")['default'],
    'Footer': typeof import("../components/Footer.vue")['default'],
    'Header': typeof import("../components/Header.vue")['default'],
    'ScrollToTop': typeof import("../components/ScrollToTop.vue")['default'],
    'Seo': typeof import("../components/Seo.vue")['default'],
    'Spinner': typeof import("../components/Spinner.vue")['default'],
    'Testimonial': typeof import("../components/Testimonial.vue")['default'],
    'ZeroData': typeof import("../components/ZeroData.vue")['default'],
    'BlogContentContainer': typeof import("../components/BlogSections/BlogContentContainer.vue")['default'],
    'BlogHeader': typeof import("../components/BlogSections/BlogHeader.vue")['default'],
    'BlogPostsList': typeof import("../components/BlogSections/BlogPostsList.vue")['default'],
    'BlogWidget': typeof import("../components/BlogSections/BlogWidget.vue")['default'],
    'BlogSectionsSingleArticle': typeof import("../components/BlogSections/SingleArticle.vue")['default'],
    'HomepageSectionsBlogSection': typeof import("../components/HomepageSections/BlogSection.vue")['default'],
    'HomepageSectionsFeaturesSection': typeof import("../components/HomepageSections/FeaturesSection.vue")['default'],
    'HomepageSectionsHeroSection': typeof import("../components/HomepageSections/HeroSection.vue")['default'],
    'HomepageSectionsTestimonialsSection': typeof import("../components/HomepageSections/TestimonialsSection.vue")['default'],
    'HomepageSectionsTwoColumnWithImageSection': typeof import("../components/HomepageSections/TwoColumnWithImageSection.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyApiTokenNotFound': typeof import("../components/ApiTokenNotFound.vue")['default'],
    'LazyBlogPostTile': typeof import("../components/BlogPostTile.vue")['default'],
    'LazyFeature': typeof import("../components/Feature.vue")['default'],
    'LazyFooter': typeof import("../components/Footer.vue")['default'],
    'LazyHeader': typeof import("../components/Header.vue")['default'],
    'LazyScrollToTop': typeof import("../components/ScrollToTop.vue")['default'],
    'LazySeo': typeof import("../components/Seo.vue")['default'],
    'LazySpinner': typeof import("../components/Spinner.vue")['default'],
    'LazyTestimonial': typeof import("../components/Testimonial.vue")['default'],
    'LazyZeroData': typeof import("../components/ZeroData.vue")['default'],
    'LazyBlogContentContainer': typeof import("../components/BlogSections/BlogContentContainer.vue")['default'],
    'LazyBlogHeader': typeof import("../components/BlogSections/BlogHeader.vue")['default'],
    'LazyBlogPostsList': typeof import("../components/BlogSections/BlogPostsList.vue")['default'],
    'LazyBlogWidget': typeof import("../components/BlogSections/BlogWidget.vue")['default'],
    'LazyBlogSectionsSingleArticle': typeof import("../components/BlogSections/SingleArticle.vue")['default'],
    'LazyHomepageSectionsBlogSection': typeof import("../components/HomepageSections/BlogSection.vue")['default'],
    'LazyHomepageSectionsFeaturesSection': typeof import("../components/HomepageSections/FeaturesSection.vue")['default'],
    'LazyHomepageSectionsHeroSection': typeof import("../components/HomepageSections/HeroSection.vue")['default'],
    'LazyHomepageSectionsTestimonialsSection': typeof import("../components/HomepageSections/TestimonialsSection.vue")['default'],
    'LazyHomepageSectionsTwoColumnWithImageSection': typeof import("../components/HomepageSections/TwoColumnWithImageSection.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  }
}
export const ApiTokenNotFound: typeof import("../components/ApiTokenNotFound.vue")['default']
export const BlogPostTile: typeof import("../components/BlogPostTile.vue")['default']
export const Feature: typeof import("../components/Feature.vue")['default']
export const Footer: typeof import("../components/Footer.vue")['default']
export const Header: typeof import("../components/Header.vue")['default']
export const ScrollToTop: typeof import("../components/ScrollToTop.vue")['default']
export const Seo: typeof import("../components/Seo.vue")['default']
export const Spinner: typeof import("../components/Spinner.vue")['default']
export const Testimonial: typeof import("../components/Testimonial.vue")['default']
export const ZeroData: typeof import("../components/ZeroData.vue")['default']
export const BlogContentContainer: typeof import("../components/BlogSections/BlogContentContainer.vue")['default']
export const BlogHeader: typeof import("../components/BlogSections/BlogHeader.vue")['default']
export const BlogPostsList: typeof import("../components/BlogSections/BlogPostsList.vue")['default']
export const BlogWidget: typeof import("../components/BlogSections/BlogWidget.vue")['default']
export const BlogSectionsSingleArticle: typeof import("../components/BlogSections/SingleArticle.vue")['default']
export const HomepageSectionsBlogSection: typeof import("../components/HomepageSections/BlogSection.vue")['default']
export const HomepageSectionsFeaturesSection: typeof import("../components/HomepageSections/FeaturesSection.vue")['default']
export const HomepageSectionsHeroSection: typeof import("../components/HomepageSections/HeroSection.vue")['default']
export const HomepageSectionsTestimonialsSection: typeof import("../components/HomepageSections/TestimonialsSection.vue")['default']
export const HomepageSectionsTwoColumnWithImageSection: typeof import("../components/HomepageSections/TwoColumnWithImageSection.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyApiTokenNotFound: typeof import("../components/ApiTokenNotFound.vue")['default']
export const LazyBlogPostTile: typeof import("../components/BlogPostTile.vue")['default']
export const LazyFeature: typeof import("../components/Feature.vue")['default']
export const LazyFooter: typeof import("../components/Footer.vue")['default']
export const LazyHeader: typeof import("../components/Header.vue")['default']
export const LazyScrollToTop: typeof import("../components/ScrollToTop.vue")['default']
export const LazySeo: typeof import("../components/Seo.vue")['default']
export const LazySpinner: typeof import("../components/Spinner.vue")['default']
export const LazyTestimonial: typeof import("../components/Testimonial.vue")['default']
export const LazyZeroData: typeof import("../components/ZeroData.vue")['default']
export const LazyBlogContentContainer: typeof import("../components/BlogSections/BlogContentContainer.vue")['default']
export const LazyBlogHeader: typeof import("../components/BlogSections/BlogHeader.vue")['default']
export const LazyBlogPostsList: typeof import("../components/BlogSections/BlogPostsList.vue")['default']
export const LazyBlogWidget: typeof import("../components/BlogSections/BlogWidget.vue")['default']
export const LazyBlogSectionsSingleArticle: typeof import("../components/BlogSections/SingleArticle.vue")['default']
export const LazyHomepageSectionsBlogSection: typeof import("../components/HomepageSections/BlogSection.vue")['default']
export const LazyHomepageSectionsFeaturesSection: typeof import("../components/HomepageSections/FeaturesSection.vue")['default']
export const LazyHomepageSectionsHeroSection: typeof import("../components/HomepageSections/HeroSection.vue")['default']
export const LazyHomepageSectionsTestimonialsSection: typeof import("../components/HomepageSections/TestimonialsSection.vue")['default']
export const LazyHomepageSectionsTwoColumnWithImageSection: typeof import("../components/HomepageSections/TwoColumnWithImageSection.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const componentNames: string[]
